import React, { useState, useMemo } from 'react';

type SortKey = 'date' | 'status' | 'risk';
type SortDirection = 'asc' | 'desc';

interface Document {
  id: number;
  name: string;
  type: string;
  date: string;
  status: string;
  risk: string;
  content?: string;
}

const UserGuideContent = `
# How to Use LexiGuard

**1. Dashboard & Analysis**
Navigate to the Dashboard. Paste any legal text (Contract, NDA, Compliance Filing) into the input box or upload a .txt file. Click "Analyze Document" to begin the AI assessment.

**2. Executive Summary**
Review the Plain English summary generated by our engine. This breaks down complex legalese into digestible bullet points for rapid decision-making.

**3. Risk Matrix**
Check the prioritized risk assessment. We categorize risks into High, Medium, and Low buckets so you know exactly where to focus your legal resources.

**4. Compliance Tracking**
Go to the Compliance tab to see your organization's ESG scores. This data updates based on your latest document analysis session.

**5. Data Security**
All sessions are temporary. Data is processed securely in real-time and is not stored on our servers after your session ends.
`;

const MockDocuments: Document[] = [
  { 
    id: 1, 
    name: 'LexiGuard_User_Manual_v1.0.txt', 
    type: 'Guide', 
    date: new Date().toISOString().split('T')[0], 
    status: 'Ready', 
    risk: 'Low',
    content: UserGuideContent
  }
];

export const DocumentsView: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [sortConfig, setSortConfig] = useState<{ key: SortKey; direction: SortDirection }>({ key: 'date', direction: 'desc' });
  const [viewDoc, setViewDoc] = useState<Document | null>(null);

  const handleSort = (key: SortKey) => {
    let direction: SortDirection = 'asc';
    if (sortConfig.key === key && sortConfig.direction === 'asc') {
      direction = 'desc';
    }
    setSortConfig({ key, direction });
  };

  const filteredAndSortedDocuments = useMemo(() => {
    let docs = [...MockDocuments];

    if (searchTerm) {
      const lowerTerm = searchTerm.toLowerCase();
      docs = docs.filter(
        (doc) => 
          doc.name.toLowerCase().includes(lowerTerm) || 
          doc.type.toLowerCase().includes(lowerTerm)
      );
    }

    const riskWeight: Record<string, number> = { 'High': 3, 'Medium': 2, 'Low': 1, '-': 0 };
    
    docs.sort((a, b) => {
      let aValue: any = a[sortConfig.key];
      let bValue: any = b[sortConfig.key];

      if (sortConfig.key === 'risk') {
        aValue = riskWeight[a.risk];
        bValue = riskWeight[b.risk];
      }

      if (aValue < bValue) return sortConfig.direction === 'asc' ? -1 : 1;
      if (aValue > bValue) return sortConfig.direction === 'asc' ? 1 : -1;
      return 0;
    });

    return docs;
  }, [searchTerm, sortConfig]);

  const SortIcon = ({ columnKey }: { columnKey: SortKey }) => {
    if (sortConfig.key !== columnKey) return <span className="ml-1 text-gray-300">↕</span>;
    return <span className="ml-1 text-brand-gold">{sortConfig.direction === 'asc' ? '↑' : '↓'}</span>;
  };

  // Helper to render "fresh" text without markdown symbols
  const renderDocumentContent = (text: string) => {
    if (!text) return null;
    
    return text.split('\n').map((line, i) => {
      // Empty lines
      if (!line.trim()) return <div key={i} className="h-4" />;
      
      // Headers
      if (line.startsWith('# ')) {
        return <h1 key={i} className="text-3xl font-serif font-bold text-slate-900 mb-6 border-b border-gray-100 pb-2">{line.replace('# ', '')}</h1>;
      }
      if (line.startsWith('## ')) {
        return <h2 key={i} className="text-xl font-serif font-bold text-slate-800 mt-6 mb-2">{line.replace('## ', '')}</h2>;
      }

      // Bolding logic: replace **text** with <strong>text</strong>
      const parts = line.split('**');
      return (
        <p key={i} className="mb-3 text-slate-700 leading-relaxed font-serif text-lg">
          {parts.map((part, idx) => 
            idx % 2 === 1 ? <strong key={idx} className="font-semibold text-slate-900">{part}</strong> : part
          )}
        </p>
      );
    });
  };

  return (
    <div className="animate-fade-in-up relative">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Document Library</h2>
          <p className="text-slate-500 text-sm">Access guides and previously analyzed documents.</p>
        </div>
        <div className="flex gap-2 w-full md:w-auto">
          <div className="relative flex-grow md:w-64">
            <input 
              type="text" 
              placeholder="Search documents..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-9 pr-4 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-slate-500 focus:border-transparent outline-none"
            />
            <svg className="w-4 h-4 text-gray-400 absolute left-3 top-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </div>
          <button className="px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-slate-600 hover:bg-gray-50 flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" />
            </svg>
            Filter
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Document Name</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                <th onClick={() => handleSort('date')} className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100 select-none">Date <SortIcon columnKey="date" /></th>
                <th onClick={() => handleSort('status')} className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100 select-none">Status <SortIcon columnKey="status" /></th>
                <th onClick={() => handleSort('risk')} className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider cursor-pointer hover:bg-gray-100 select-none">Risk Level <SortIcon columnKey="risk" /></th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredAndSortedDocuments.length > 0 ? (
                filteredAndSortedDocuments.map((doc) => (
                  <tr key={doc.id} className="hover:bg-slate-50 transition-colors group">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex-shrink-0 h-8 w-8 bg-slate-100 rounded flex items-center justify-center text-slate-500 group-hover:bg-white group-hover:text-brand-gold transition-colors">
                          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                          </svg>
                        </div>
                        <div className="ml-4"><div className="text-sm font-medium text-slate-900">{doc.name}</div></div>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap"><div className="text-sm text-slate-500">{doc.type}</div></td>
                    <td className="px-6 py-4 whitespace-nowrap"><div className="text-sm text-slate-500">{doc.date}</div></td>
                    <td className="px-6 py-4 whitespace-nowrap"><span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${doc.status === 'Ready' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}`}>{doc.status}</span></td>
                    <td className="px-6 py-4 whitespace-nowrap"><span className={`text-sm font-medium ${doc.risk === 'High' ? 'text-red-600' : doc.risk === 'Medium' ? 'text-orange-500' : doc.risk === 'Low' ? 'text-emerald-600' : 'text-gray-400'}`}>{doc.risk}</span></td>
                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <button onClick={() => setViewDoc(doc)} className="text-slate-600 hover:text-brand-gold">View</button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr><td colSpan={6} className="px-6 py-8 text-center text-sm text-slate-500 italic">No documents found matching "{searchTerm}"</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Enhanced Document Viewer Modal */}
      {viewDoc && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-md" onClick={() => setViewDoc(null)}></div>
          
          <div className="relative bg-white w-full max-w-3xl rounded-xl shadow-2xl animate-fade-in-up flex flex-col max-h-[90vh] overflow-hidden border border-gray-200">
            {/* Modal Header */}
            <div className="px-8 py-5 border-b border-gray-100 flex justify-between items-center bg-white z-10">
              <div>
                <h3 className="text-lg font-bold text-slate-900">{viewDoc.name}</h3>
                <div className="flex items-center gap-2 mt-1">
                   <span className="text-xs font-mono text-slate-500 bg-gray-100 px-2 py-0.5 rounded">ID: #{viewDoc.id}</span>
                   <span className="text-xs text-slate-400">{viewDoc.date}</span>
                </div>
              </div>
              <button 
                onClick={() => setViewDoc(null)}
                className="text-slate-400 hover:text-slate-700 hover:bg-slate-100 p-2 rounded-full transition-all"
              >
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            {/* Document Body - Scrollable */}
            <div className="flex-1 overflow-y-auto bg-slate-50/50">
              <div className="max-w-2xl mx-auto px-8 py-10 bg-white min-h-full shadow-sm my-6 rounded border border-gray-100">
                 {viewDoc.content && renderDocumentContent(viewDoc.content)}
              </div>
            </div>

            {/* Modal Footer */}
            <div className="px-8 py-4 border-t border-gray-100 bg-white flex justify-between items-center">
              <span className="text-xs text-slate-400 font-medium">Confidential - Internal Use Only</span>
              <button 
                onClick={() => setViewDoc(null)}
                className="px-5 py-2 bg-slate-900 text-white text-sm font-medium rounded-lg hover:bg-slate-800 transition-colors shadow-sm"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};